name: Publish Packages

on:
  push:
    tags:
      - 'Optional-*'


env:
  Project: src/Optional
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/deskdirector/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ${{ env.Project }} --configuration Release --no-restore
    - name: Test
      run: dotnet test "tests/Optional.Tests/Optional.Tests.csproj" --configuration Release --no-restore --verbosity normal
    - name: Publish to GPR
      run: dotnet nuget push "${{ env.Project }}/bin/Release/*.symbols.nupkg"
